### ISSUE TITLE
I'm not able to create a Branch for the NeedIt-kingston

### ISSUE THREAD

**Issue by rattanalekskulchai** [ServiceNow/devtraining-needit-kingston#8]
I'm getting an error "The user only has read access to the repo.  Make sure the user has both read and write access".

**Comment by sar-coder** [comment]
IMPORTANT: If the branch creation fails and you see a message about 
confirming the user has read, write, and create branch access, it means 
you connected Studio to the ServiceNow version of the repository and not 
your forked version of the repository. In Studio, open the*Source 
Control > Edit Repository Configuration*menu item and re-configure the 
connection between Studio and your forked repository.

**Comment by rattanalekskulchai** [comment]
Thank you for a quick respond.  I might have missed the Fork step, trying it now.

**Comment by sar-coder** [comment]
No problem, just need to be pointing to your own repository. Have fun!
